Chore/upgrade marshmallow 4 (#1450)
* fix: default format is already iso

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: use `validate` rather than `validator`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: use `load_default` rather than `default`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: use `load_from` rather than `data_key`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "fix: use `load_from` rather than `data_key`"

This reverts commit ddc536f1aeff1cf1d768d2b99d816ec52de42d21.

* chore: unpin marshmallow and update to 4.0.0

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: @validates decorated methods now receive data_key as a keyword argument

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: load_default values now lead to the field being in the data, even when the default is None

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: avoid load_default=None instead, especially in combination with required=False

Signed-off-by: F.N. Claessen <felix@seita.nl>

* tiny refactoring

* Fixed: New Context API.

* Remove obsolete API blueprint 'play' as well as backup code (#1622)

* remove obsolote API blueprint 'play' as well as file/folder - based backup functionality

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* add changelog entry

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* add changelog entries for API and CLI

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* remove line about /restoreData from docs

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

---------

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* Feat: Added KPIs for sensors. (#1608)

* Added KPIs for sensors.

* UI fixes.

* Schema Validation added and tiny refactoring in the UI message.

* Sensor resolution validation.

* Added test cases.

* Resolved Felix's comments.

* Miscelaneous changes.

* Fixed failing test cases.

* Updated changelog.

* Changed db nullable=False and some other UI changes.

* Documented teh function.

---------

Co-authored-by: Nicolas Höning <nicolas@seita.nl>

* Fix/per kWh price sensors in flex context (#1628)

* feat: add test case covering flex-context sensors sharing the same unit

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: do not convert share currency unit to base units

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: no conversion needed if not converting to base units

Signed-off-by: F.N. Claessen <felix@seita.nl>

* feat: test shared SEK/MWh, too

Signed-off-by: F.N. Claessen <felix@seita.nl>

* feat: check mixing SEK/kWh with SEK/MWh, too

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: add field name to ValidationError

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: changelog entry

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: update test expectations

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "refactor: no conversion needed if not converting to base units"

This reverts commit 1375efc5e09ad89cd64c15642687aecc47e1323f.

* Revert "fix: do not convert share currency unit to base units"

This reverts commit 89b4b1a4773ee3e9bcb34d30aeca178145c92286.

* Revert "fix: update test expectations"

This reverts commit 035827800caedb74b999dedc629ae4b9e95fd697.

* feat: convert compatible units to support mixed price units like SEK/MWh with SEK/kWh

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: tests

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: derive shared currency unit from deprecated fields, for backwards compatibility

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: use static class util method

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: simplify using walrus operator

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: simplify using string concatenation

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: add docstring and doctests

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Fix/stop registering play blueprint (#1630)

* fix: prevent failing on registering removed blueprint

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: changelog entry

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: F.N. Claessen <felix@seita.nl>

* UI/Fix a few issues with asset creation  (#1629)

* inject parent asset Id in error-induced asset form reload

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* make asset view/form more robust for no account or parent asset, while re-displaying forms when validation errors occur

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* When adding child assets, pre-fill and display parent asset's location

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* remove extra styling for security messages - they have their own class, and if it's success an infor around it looks bad (example: succcessful 2FA step)

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* add changelog entry

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* remove lines no longer needed

Signed-off-by: Nicolas Höning <nicolas@seita.nl>

* refactor: simplify tuple to JSON (array)

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: zoom out (sync with default zoom level of dashboard) for better context of new geolocation within existing asset portfolio

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: Nicolas Höning <nicolas@seita.nl>
Signed-off-by: F.N. Claessen <felix@seita.nl>
Co-authored-by: F.N. Claessen <felix@seita.nl>

* Fixed sensor page failing on getAssetKPIs. (#1633)

* Added data_key.

* fix: update test for new exception type

Signed-off-by: F.N. Claessen <felix@seita.nl>

* chore/upgrade-marshmallow-only-with-python-3.11-and-above

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "chore/upgrade-marshmallow-only-with-python-3.11-and-above"

This reverts commit b73846800bf8459db3a1233f52034c354e0a955c.

* fix: tests failing with `TypeError: Start and end cannot both be tz-aware with different timezones`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: test failing with `ValueError: Both dates must have the same UTC offset`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: some tests use timezone naive datetimes

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: changelog entry

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: AttributeError: 'datetime.datetime' object has no attribute 'tz'

Signed-off-by: F.N. Claessen <felix@seita.nl>

* chore: PytestRemovedIn9Warning: Marks applied to fixtures have no effect

Signed-off-by: F.N. Claessen <felix@seita.nl>

* feat: compatibility with both Marshmallow 3 and 4

Signed-off-by: F.N. Claessen <felix@seita.nl>

* chore/upgrade-marshmallow-only-with-python-3.11-and-above

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: add inline comments explaining if/else

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: move import statements to top

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "fix: AttributeError: 'datetime.datetime' object has no attribute 'tz'"

This reverts commit 2c3c6650e2237aad3f948b736df188cf4077f449.

* Revert "fix: some tests use timezone naive datetimes"

This reverts commit aa30bbdb643a1bfb1d209622a4a2ee650e0c500b.

* Revert "fix: test failing with `ValueError: Both dates must have the same UTC offset`"

This reverts commit 589bd01fbd2fe945ca80b2e4bbdba28606462b64.

* Removed unncessary SchemaContext.

Signed-off-by: Muhammad-Moiz626 <muhammadmoiz4843@gmail.com>

* Updated the comnment.

* refactor: more DRY

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: even more DRY

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: stop getting the asset from the schema context

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: F.N. Claessen <felix@seita.nl>
Signed-off-by: Nicolas Höning <nicolas@seita.nl>
Signed-off-by: Muhammad-Moiz626 <muhammadmoiz4843@gmail.com>
Co-authored-by: Nicolas Höning <nicolas@seita.nl>
Co-authored-by: Muhammad-Moiz626 <muhammadmoiz4843@gmail.com>